.Phony:clear
clear:
	rm -rf *.class ./Figure/*.class ./Figure/BaseFigure/*.class ./Figure/BaseFigure/Circle/*.class ./Figure/BaseFigure/Square/*.class ./Figure/BaseFigure/Triangle/*.class ./Frame/*.class 